# Generated by Django 3.0.6 on 2020-05-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='image_id',
            new_name='image',
        ),
    ]
