# Generated by Django 3.0.6 on 2020-05-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20200509_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='label_probability',
            new_name='probability',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='top_left_x_coordinate',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='top_left_y_coordinate',
            new_name='y',
        ),
    ]
