# Generated by Django 3.0.6 on 2020-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20200509_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='manual_labelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.FloatField(),
        ),
    ]
